# Generated by Django 5.2.15 on 2026-06-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='batches/'),
        ),
    ]
