# Generated by Django 5.0.14 on 2026-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Designates whether the user can access to Developer Portal.'),
        ),
    ]
