# Generated by Django 6.0.1 on 2026-01-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
    ]
