# Generated by Django 5.0.14 on 2026-01-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_is_bank_testsession_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('verbal', 'Verbal IQ'), ('non-verbal', 'Non-Verbal IQ'), ('wat', 'Word Association (WAT)')], db_index=True, default='verbal', max_length=20),
        ),
    ]
