# Generated by Django 5.0.14 on 2026-01-17 18:41

from django.db import migrations

def create_sample_test(apps, schema_editor):
    Test = apps.get_model('tests', 'Test')
    User = apps.get_model('users', 'User')
    
    # Try to find an existing sample test
    if Test.objects.filter(is_free_sample=True).exists():
        return

    # Try to find a default user (admin or any user) to assign as creator
    admin = User.objects.filter(role='admin').first()
    if not admin:
        admin = User.objects.filter(is_superuser=True).first()
    
    # If no user exists, we can't easily create a test with a foreign key constraint
    # But usually there is at least one user. If not, we might skip or fail.
    # For safety, we skip if no user found (though unlikely in prod)
    if not admin:
        return

    Test.objects.create(
        name="Free Sample IQ Test",
        description="A quick 10-minute assessment to gauge your IQ level. Try it now for free!",
        category="verbal",
        duration_minutes=10,
        price=0.00,
        is_active=True,
        is_free_sample=True,
        is_bank=False,
        passing_score=60,
        total_questions=20,
        created_by=admin
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_fix_misplaced_test_categories'),
        ('users', '0003_user_is_developer'), 
    ]

    operations = [
        migrations.RunPython(create_sample_test),
    ]
